webpage/urls.py
from django.conf.urls import url
from . import views
from .models import User
app_name = 'webpage'

db = User.objects.all()

urlpatterns = [

    url(r'^$', views.index , name='index'),

    url(r'^(?P<names>[a-z,A-Z]+)/$', views.Profile , name='profile'),

    url(r'^user/Details/$', views.Details , name='Details'),

    url(r'^(?P<names>[a-z,A-Z]+)/Images$', views.Images , name='Images'),

    url(r'^user/(?P<pk>[0-9]+)/AddImage/$', views.AddImage.as_view() , name='AddImage'),

    url(r'^user/Massages/$', views.Massages , name='Massages'),

    url(r'^user/AddMassages/$', views.AddMassage.as_view() , name='AddMassages'),

    url(r'^(?P<names>[a-z,A-Z]+)/Data$', views.Data , name='Data'),

    url(r'^user/(?P<pk>[0-9]+)/AddData/$', views.AddData.as_view() , name='AddData'),

    url(r'^user/reg/$', views.UserFormView.as_view() , name='reg'),

    url(r'^user/login/$', views.login_user, name='login'),

    url(r'^user/logout/$', views.logout_user, name='logout'),

    url(r'^user/Add/$', views.AddUser.as_view() , name='AddUser'),

    url(r'^user/(?P<pk>[0-9]+)/$', views.UpdateUser.as_view() , name='UpdateUser'),

    url(r'^user/(?P<pk>[0-9]+)/Delete/$', views.DeleteUser.as_view() , name='DeleteUser'),



]

website/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^webpage/', include('webpage.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

webpage/models.py
from __future__ import unicode_literals
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import Permission, User

# Create your models here.

class profile(models.Model):
    user1 = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length = 40)
    nick_name = models.CharField(max_length = 20)
    def get_absolute_url(self):
        return reverse('webpage:profile',kwargs = { 'names' : self.nick_name})
    def __str__(self):
        return self.name


class Data(models.Model):
    user2 = models.ForeignKey(profile,on_delete = models.CASCADE)
    about= models.CharField(max_length = 200)
    email = models.EmailField()
    mobile= models.CharField(max_length = 200)
    def __str__(self):
        return self.about

class images(models.Model):
    user3 = models.ForeignKey(profile,on_delete = models.CASCADE)
    images_details = models.CharField(max_length = 200)
    images = models.CharField(max_length = 200)
    def __str__(self):
        return self.images

class Massage(models.Model):
    user4 = models.ForeignKey(User, on_delete = models.CASCADE)
    sub = models.CharField(max_length = 200)
    massage = models.CharField(max_length = 200)
    def __str__(self):
        return self.massage

webpage/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

webpage/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic.edit import CreateView,UpdateView, DeleteView
from django.contrib.auth import authenticate,login
from django.views.generic import View
from .forms import UserForm
from django.contrib.auth.models import User
from django.contrib.auth import logout
from .models import profile,Data,images,Massage

def index(request):
    if not request.user.is_authenticated:
        return render(request, 'webpage/login.html')
    else:
        db = profile.objects.filter(user1 = request.user)
        return render(request, 'webpage/index.html' , {'db':db})

def Profile(request, names):
    if not request.user.is_authenticated:
        return render(request, 'webpage/login.html')
    else:
        db = get_object_or_404(profile,nick_name__iexact = str(names),user1 = request.user)
        return render(request, 'webpage/profile.html' , {'db':db})

def Details(request):
    if not request.user.is_authenticated:
        return render(request, 'webpage/login.html')
    else:
        db = profile.objects.filter(user1 = request.user)
        return render(request, 'webpage/user_profile.html' ,{ 'db':db} )

class AddUser(CreateView):
        model= profile
        fields = ['user1','name','nick_name']

class UpdateUser(UpdateView):
        model= profile
        fields = ['user1','name','nick_name']

class DeleteUser(DeleteView):
        model= profile
        success_url = reverse_lazy('webpage:index')

class UserFormView(View):
    form_class = UserForm
    template_name = 'webpage/reg.html'

    def get(self,request):
        form = self.form_class(None)
        return render (request,self.template_name , {'form' :form })

    def post(self,request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            # normalised data_set
            username = form.cleaned_data ['username']
            password = form.cleaned_data ['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=username,password=password)
            if user is not None:

                if user.is_active:
                    login(request,user)
                    return redirect ('webpage:index')
        return render(request, self.template_name , {'form': form})

def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                db = profile.objects.filter(user1=request.user)
                return render(request, 'webpage/index.html', {'db' : db})
            else:
                return render(request, 'webpage/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'webpage/login.html', {'error_message': 'Invalid login'})
    return render(request, 'webpage/login.html')

def logout_user(request):
    if not request.user.is_authenticated:
        return render(request, 'webpage/login.html')
    else:
        logout(request)
        form = UserForm(request.POST or None)
        context = {
            "form": form,
        }
        return render(request, 'webpage/login.html', context)

class AddImage(CreateView):
        model= images
        fields = ['user3','images_details','images']
        success_url = reverse_lazy('webpage:index')

def Images(request, names):
    if not request.user.is_authenticated:
        return render(request, 'webpage/login.html')
    else:
        db = get_object_or_404(profile,nick_name__iexact = str(names))
        return render(request, 'webpage/Images.html' , {'db':db})

class AddData(CreateView):
        model= Data
        fields = ['user2','about','email', 'mobile']
        success_url = reverse_lazy('webpage:index')

def Data(request, names):
    if not request.user.is_authenticated:
        return render(request, 'webpage/login.html')
    else:
        db = get_object_or_404(profile,nick_name__iexact = str(names))
        return render(request, 'webpage/About.html' , {'db':db})

class AddMassage(CreateView):
        model= Massage
        fields = ['user4','sub','massage']
        success_url = reverse_lazy('webpage:index')

def Massages(request):
    if not request.user.is_authenticated:
        return render(request, 'webpage/login.html')
    else:
        return render(request, 'webpage/Massages.html' )

webpage/templates/webpage/About.html
{% extends "webpage/base.html" %}

{% block title  %}About Mr {{db.name}}{% endblock  %}

{% block body  %}


<div id="images">

<h3> Here is something about you </h3><br>

{%if db.data_set.all%}
        <div id="images">
        {% for logo in db.data_set.all %}
                    <p> {{logo.about}}</p>
                    <p> {{logo.mobile}}</p>
                    <p> {{logo.email}}</p>
        {% endfor %}
      </div>
{% else %}
        <h3> Sorry Updade First </h3><br> <br> <br>


{%endif%}

</div>


{% endblock  %}

webpage/templates/webpage/AddUser.html
<div id="adduser">
<br>
{% for field in form  %}
    <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
              <span class="text-danger small"> {{field.errors}} </span>
          </div>
          <label class="control-label col-sm-2">  {{field.label_tag}} </label>
          <div class="col-sm-10"> {{field}} </div>
    </div>
{% endfor %}
</div>

webpage/templates/webpage/Images.html
{% extends "webpage/base.html" %}

{% block title  %}Profile of Mr {{db.name}}{% endblock  %}

{% block body  %}


<div id="images">

<h3> Here is your pics </h3><br>

{%if db.images_set.all%}
        <div id="images">
        {% for logo in db.images_set.all %}
                    <p> {{logo.images_details}}</p>
                    <img src="{{logo.images}}" height="200" width="200"/>                                                                                                                                <br>  <br>
        {% endfor %}
      </div>
{% else %}
        <h3> Sorry No Pics </h3><br> <br> <br>


{%endif%}

</div>


{% endblock  %}

webpage/templates/webpage/Massages.html
{% extends "webpage/base.html" %}

{% block title  %}Massages{% endblock  %}

{% block body  %}


<div id="images">

<h3> Here is some messages for you </h3><br>

{%if request.user.massage_set.all   %}
        <div id="images">
        {% for logo in request.user.massage_set.all %}
                    <p> {{logo.sub}}</p>
                    <p> {{logo.massage}}</p> <br> <br>
        {% endfor %}
      </div>
{% else %}
        <h3> Sorry Updade First </h3><br> <br> <br>


{%endif%}

</div>


{% endblock  %}

webpage/templates/webpage/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title  %}Chat On{% endblock  %}</title>

    {% load staticfiles %}
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js">
    <link rel="stylesheet" type="text/css" href= "{% static '/webpage/style.css' %}">
  </head>


  <body>
          <nav class="navbar navbar-inverse">
                    <div class="collapse navbar-collapse" id="#topNavbar">
                            <ul class="nav navbar-nav">
                                    <li class="">
                                          <a href="{% url 'webpage:index' %}">
                                            <span class = "glyphicon glyphicon-home" area-hidden = "true" > </span> &nbsp;Home
                                          </a>
                                    </li>

                                    <li class="">
                                          <a href="{% url 'webpage:Details' %}">
                                            <span class = "glyphicon glyphicon-user" area-hidden = "true" > </span> &nbsp;Profile
                                          </a>
                                    </li>
                            </ul>

                            <form class="navbar-form navbar-left" action="#" role="search" method="get">
                                    <div class="form-group">
                                      <input type="text" class="form-control" name="q" value="">
                                    </div>
                                    <button class="btn btn-default" type="submit">Search</button>
                            </form>

                 <!-- Right side -->

                             <ul class="nav navbar-nav navbar-right">
                                   <li class="">
                                         <a href="{% url 'webpage:AddUser' %}">
                                           <span class = "glyphicon glyphicon-plus" area-hidden = "true" > </span> &nbsp; Add contacts
                                         </a>
                                   </li>

                                   <li class="">
                                         <a href="{% url 'webpage:logout' %}">
                                           <span class = "glyphicon glyphicon-off" area-hidden = "true" > </span> &nbsp; Logout
                                         </a>
                                   </li>
                             </ul>

                    </div>
          </nav>


          {% block body  %}

          {% endblock  %}

  </body>
</html>

webpage/templates/webpage/base_login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title  %}Login Page{% endblock  %}</title>

    {% load staticfiles %}
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js">
    <link rel="stylesheet" type="text/css" href= "{% static '/webpage/style.css' %}">
  </head>


  <body>
          <nav class="navbar navbar-inverse">
                    <div class="collapse navbar-collapse" id="#topNavbar">
                            <ul class="nav navbar-nav">
                                    <li class="">
                                          <a href="{% url 'webpage:login' %}">
                                            <span class = "glyphicon glyphicon-home" area-hidden = "true" > </span> &nbsp;Login
                                          </a>
                                    </li>

                                    <li class="">
                                          <a href="{% url 'webpage:reg' %}">
                                            <span class = "glyphicon glyphicon-user" area-hidden = "true" > </span> &nbsp;Register
                                          </a>
                                    </li>
                            </ul>



                    </div>
          </nav>


          {% block body  %}

          {% endblock  %}

  </body>
</html>

webpage/templates/webpage/data_form.html
{% extends "webpage/base.html" %}

{% block title  %} AddUser {% endblock  %}

{% block body  %}

<div class="container-fluid">

    <form class="form-horizontal", action="", method="post" ,enctype="multipart/form-data">
          {% csrf_token %}
          {% include "webpage/AddUser.html" %}
          <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                    <br>
                    <button type="submit" class="btn btn-success"> Save </button>

              </div>
          </div>
    </form>

</div>

{% endblock  %}

webpage/templates/webpage/images_form.html
{% extends "webpage/base.html" %}

{% block title  %} AddUser {% endblock  %}

{% block body  %}

<div class="container-fluid">

    <form class="form-horizontal", action="", method="post" ,enctype="multipart/form-data">
          {% csrf_token %}
          {% include "webpage/AddUser.html" %}
          <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                    <br>
                    <button type="submit" class="btn btn-success"> Add </button>

              </div>
          </div>
    </form>

</div>

{% endblock  %}

webpage/templates/webpage/login.html
{% extends "webpage/base_login.html" %}

{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}

<div id="login">

<div id="register">

<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">

                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'webpage:login'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>


                    Don't have an account? <a href="{% url 'webpage:reg' %}">Click here</a> to register.

            </div>
        </div>
    </div>

</div>

</div>

</div>

{% endblock %}

webpage/templates/webpage/massage_form.html
{% extends "webpage/base.html" %}

{% block title  %} Send Massage {% endblock  %}

{% block body  %}

<div class="container-fluid">

    <form class="form-horizontal", action="", method="post" ,enctype="multipart/form-data">
          {% csrf_token %}
          {% include "webpage/AddUser.html" %}
          <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                    <br>
                    <button type="submit" class="btn btn-success"> Send </button>

              </div>
          </div>
    </form>

</div>

{% endblock  %}

webpage/templates/webpage/profile.html
{% extends "webpage/base.html" %}

{% block title  %}Profile of Mr {{db.name}}{% endblock  %}

{% block body  %}

    <div id="profile">
          <a href ="/webpage/user/{{db.id}}/"> Update Profile </a> <br> <br>
          <a href ="/webpage/user/{{db.id}}/AddData/"> Update About </a> <br> <br>
          <a href ="/webpage/{{db.nick_name}}/Data"> About </a> <br> <br>

          {%if Error_massage%}
                  <h3> {{Error_massage}} </h3>
           {%endif%}
      </div>
{% endblock  %}

webpage/templates/webpage/profile_form.html
{% extends "webpage/base.html" %}

{% block title  %} AddUser {% endblock  %}

{% block body  %}

<div class="container-fluid">

    <form class="form-horizontal", action="", method="post" ,enctype="multipart/form-data">
          {% csrf_token %}
          {% include "webpage/AddUser.html" %}
          <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                    <br>
                    <button type="submit" class="btn btn-success"> Add </button>

              </div>
          </div>
    </form>

</div>

{% endblock  %}

webpage/templates/webpage/register.html
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include '/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'music:login_user' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

webpage/templates/webpage/user_profile.html
{% extends "webpage/base.html" %}

<title>{% block title  %}Chat On{% endblock  %}</title>

{% block body %}
<div class="albums-container container-fluid">

    <div class="row">
        <div class="col-sm-12">
            <h4>Here is Your Profile -- {{ user.username }} </h4>
            <h4>Here is Your Email -- {{ user.email }} </h4>
            <h3> Here are your Contacts</h3>
            <br>
        </div>
        {% if db %}
            {% for contacts in db %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        {% if contacts.images_set.all %}
                              {% for  dp1 in contacts.images_set.all %}
                                    {% if not forloop.counter0	%}
                                          <a href="{% url 'webpage:profile' contacts.nick_name %}">
                                              <img src="{{dp1.images}}" height="250" width="200"/>
                                          </a>
                                     {%endif%}
                              {% endfor %}

                         {% else %}
                               <a href="{% url 'webpage:profile' contacts.nick_name %}">
                                   <img src="http://www.hit4hit.org/img/login/user-icon-6.png" height="200" width="200"/> <br>
                               </a>
                         {%endif%}


                        <div class="caption">
                            <h2>{{ contacts.name }}</h2>
                            <h4>{{ contacts.nick_name }}</h4>

                         
                            <a href="{% url 'webpage:AddUser'  %}" class="btn btn-primary btn-sm" role="button">Add</a>
                            <a href="{% url 'webpage:UpdateUser'  contacts.id %}" class="btn btn-primary btn-sm" role="button">Update</a>

                         
                            <form action="{% url 'webpage:DeleteUser' contacts.id %}" method="post" style="display: inline">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ contacts.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                          

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'webpage:AddUser' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add a Profile
                    </button>
                </a>
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}